on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
  #        - 1.40.0  # MSRV
        include:
          - rust: nightly
            experimental: true
        mcu:
          - stm32h743
          - stm32h753
          - stm32h743v
          - stm32h753v
          - stm32h747cm7

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: thumbv6m-none-eabi
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --examples --target thumbv7em-none-eabihf --features rt,${{ matrix.mcu }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib --target x86_64-unknown-linux-gnu --features rt,${{ matrix.mcu }}
